#!/usr/bin/env bash
screenshot_blur () {
  import -quality 0 -quiet -window root png:- |\
    convert -thumbnail 4% -sample 2500% - -
}

lock() {
  screenshot_blur | i3lock -e -f -i /dev/stdin
}

case "$1" in
    lock)
	lock
	;;
    exit)
	i3-msg exit
	;;
    suspend)
	lock && sleep 0.13 && systemctl suspend
	;;
    reboot)
	systemctl reboot
	;;
    poweroff)
	systemctl poweroff
	;;
    *)
	echo "Usage: $0 {lock|exit|suspend|reboot|poweroff}"
	exit 2
esac

exit 0
