alias ls="ls --color=auto -a"
alias mount="sudo mount"
alias umount="sudo umount"
alias xclip="xclip -selection c"
alias xpaste="xclip -selection clipboard -o"
alias shutdown="sudo shutdown"
alias reboot="sudo reboot"
