#!/bin/sh
#
# Run all dotfiles installers.

cd "$(dirname $0)"/..


# find the installers and run them iteratively
find . -name install.sh | ( export APPS=""
while read installer
	do
		. "${installer}"
	done
	sudo pacman -S $APPS</dev/tty )
