#!/usr/bin/env bash

lock() {
  _lockscreen="/run/user/$(id -u)/swaylock.png"
  grim - | convert - -thumbnail 4% -sample 2500% $_lockscreen
  #convert -depth 8 -size 1920x1080 rgba:- -flip -thumbnail 4% -sample 2500% $_lockscreen
  swaylock -e --scaling=stretch -i $_lockscreen &
}

case "$1" in
  lock)
    lock
    ;;
  exit)
    swaymsg exit
    ;;
  suspend)
    lock
    sleep 0.09
    systemctl suspend
    ;;
  reboot)
    systemctl reboot
    ;;
  poweroff)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|exit|suspend|reboot|poweroff}"
    exit 2
esac

exit 0
